// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

function pickEnv(keys: string[]): string | undefined {
  for (const key of keys) {
    const value = process.env[key];
    if (value && value.trim()) return value.trim();
  }
  return undefined;
}

function buildPostgresUrlFromParts(): string | undefined {
  const host = pickEnv(["PGHOST", "POSTGRES_HOST", "POSTGRESQL_HOST"]);
  const port = pickEnv(["PGPORT", "POSTGRES_PORT", "POSTGRESQL_PORT"]) ?? "5432";
  const database = pickEnv([
    "PGDATABASE",
    "POSTGRES_DB",
    "POSTGRES_DATABASE",
    "POSTGRESQL_DATABASE",
  ]);
  const user = pickEnv(["PGUSER", "POSTGRES_USER", "POSTGRESQL_USER"]);
  const password = pickEnv(["PGPASSWORD", "POSTGRES_PASSWORD", "POSTGRESQL_PASSWORD"]);

  if (!host || !database || !user) return undefined;

  const auth = password
    ? `${encodeURIComponent(user)}:${encodeURIComponent(password)}`
    : `${encodeURIComponent(user)}`;

  return `postgresql://${auth}@${host}:${port}/${database}`;
}

const databaseUrl =
  pickEnv([
    "DATABASE_URL",
    "DATABASE_PRIVATE_URL",
    "POSTGRES_URL",
    "POSTGRESQL_URL",
    "RAILWAY_DATABASE_URL",
  ]) ?? buildPostgresUrlFromParts();

if (!databaseUrl) {
  // eslint-disable-next-line no-console
  console.error(
    "[prisma.config] Missing database URL. Set DATABASE_URL (recommended) in Railway Variables."
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
